---
- name: Detect Surface device
  set_fact:
    is_surface: >-
      {{
        (
          ansible_facts.get('system_vendor','') | lower
        ).find('microsoft') != -1
        and
        (
          ansible_facts.get('product_name','') | lower
        ).find('surface') != -1
      }}

- name: If Surface device
  include_tasks: if_surface.yml
  when: is_surface
